version: '3.9'
services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ch_data:/var/lib/clickhouse
      - ch_log:/val/log/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"

volumes:
    ch_data:
    ch_log:
