version: '3.9'
services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    deploy:
      resources:
        limits:
          cpus: '16'
          memory: 100G
        reservations:
          cpus: '8'
          memory: 50G
    volumes:
      - ch_data:/var/lib/clickhouse
      - ch_log:/val/log/clickhouse-server
      - type: bind
        read_only: true
        source: ./config.d/custom_config.xml
        target: /etc/clickhouse-server/config.d/custom_config.xml
    environment:
      # This limits Clickhouse's memory to 30% of the host memory
      # If you have high volume and your search return incomplete results
      # You might want to change this to a higher value (and ensure your host has enough memory)
      MAX_MEMORY_USAGE_RATIO: ${MAX_MEMORY_USAGE_RATIO}
    ports:
      - ${CLICKHOUSE_PORT}:8123
      - ${CLICKHOUSE_CLIENT_PORT}:9000

volumes:
    ch_data:
    ch_log:
